-- =====================================================================
-- SAUVEGARDE – schéma « anglais » du collègue d'Arthur (compte kimijohson@gmail.com), état du 08/10/2026
-- (créé le 08/10 vers 11 h 27, hors de l'appli Laravel ; auteur à confirmer dans le groupe)
-- Finalement CONSERVÉ (non supprimé). Seule modification : accès anonyme retiré aux 6 fonctions SECURITY DEFINER.
-- Ce fichier permet de le recréer si besoin (exécuter dans Supabase > SQL Editor).
-- Contenu au 08/10 : 0 demande, 0 pièce jointe, 0 projet,
-- 1 employé (compte Supabase Auth kimijohson@gmail.com, admin), 4 types, 2 règles de rôle, 1 log.
-- =====================================================================

create type public.app_role as enum ('admin','direction','manager','rh','dev','commercial','comptable','employee');
create type public.request_status as enum ('pending','validated','refused','expired');
create type public.attachment_type as enum ('doc','photo','audio','video');

create table public.employees (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  first_name text, last_name text, phone text,
  role public.app_role not null default 'employee',
  manager_id uuid references public.employees(id) on delete set null,
  created_at timestamptz not null default now()
);
create table public.role_rules (
  id serial primary key,
  match_type text not null check (match_type in ('email','domain')),
  match_value text not null,
  role public.app_role not null,
  unique (match_type, match_value)
);
create table public.request_types (code text primary key, label text not null, default_days integer not null default 7);
create table public.requests (
  id uuid primary key default gen_random_uuid(),
  employee_id uuid not null default auth.uid() references public.employees(id),
  type text not null references public.request_types(code),
  description text,
  status public.request_status not null default 'pending',
  manager_id uuid references public.employees(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deadline timestamptz
);
create table public.attachments (
  id uuid primary key default gen_random_uuid(),
  request_id uuid not null references public.requests(id) on delete cascade,
  file_url text not null,
  type public.attachment_type not null,
  created_at timestamptz not null default now()
);
create table public.projects (
  id uuid primary key default gen_random_uuid(),
  name text not null, revenue numeric not null default 0,
  manager_id uuid references public.employees(id)
);
create table public.audit_logs (
  id bigint generated by default as identity primary key,
  user_id uuid, action text not null, entity text, entity_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

CREATE OR REPLACE FUNCTION public.my_role() RETURNS public.app_role LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO '' AS $function$
  select role from public.employees where id = auth.uid();
$function$;

CREATE OR REPLACE FUNCTION public.resolve_role(p_email text) RETURNS public.app_role LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO '' AS $function$
  select coalesce(
    (select role from public.role_rules where match_type='email' and lower(match_value)=lower(p_email) limit 1),
    (select role from public.role_rules where match_type='domain' and lower(match_value)=lower(split_part(p_email,'@',2)) limit 1),
    'employee'::public.app_role);
$function$;

CREATE OR REPLACE FUNCTION public.handle_new_user() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path TO '' AS $function$
begin
  insert into public.employees (id, email, first_name, last_name, phone, role)
  values (new.id, new.email, new.raw_user_meta_data->>'first_name', new.raw_user_meta_data->>'last_name',
          new.raw_user_meta_data->>'phone', public.resolve_role(new.email));
  insert into public.audit_logs (user_id, action, entity, entity_id, metadata)
  values (new.id, 'signup', 'employees', new.id::text, jsonb_build_object('email', new.email));
  return new;
end $function$;

CREATE OR REPLACE FUNCTION public.log_login() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path TO '' AS $function$
begin
  if new.last_sign_in_at is distinct from old.last_sign_in_at then
    insert into public.audit_logs (user_id, action, entity, entity_id) values (new.id, 'login', 'employees', new.id::text);
  end if;
  return new;
end $function$;

CREATE OR REPLACE FUNCTION public.audit_requests() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path TO '' AS $function$
begin
  if tg_op = 'INSERT' then
    insert into public.audit_logs (user_id, action, entity, entity_id, metadata)
    values (auth.uid(), 'create_request', 'requests', new.id::text,
            jsonb_build_object('type', new.type, 'manager_id', new.manager_id, 'deadline', new.deadline));
  else
    insert into public.audit_logs (user_id, action, entity, entity_id, metadata)
    values (auth.uid(),
            case when new.status is distinct from old.status then
              case new.status when 'validated' then 'validate_request' when 'refused' then 'refuse_request'
                              when 'expired' then 'expire_request' else 'update_request' end
            else 'update_request' end,
            'requests', new.id::text, jsonb_build_object('status_old', old.status, 'status_new', new.status));
  end if;
  return new;
end $function$;

CREATE OR REPLACE FUNCTION public.audit_attachments() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path TO '' AS $function$
begin
  insert into public.audit_logs (user_id, action, entity, entity_id, metadata)
  values (auth.uid(), 'upload_file', 'attachments', new.id::text,
          jsonb_build_object('request_id', new.request_id, 'type', new.type, 'file_url', new.file_url));
  return new;
end $function$;

CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
CREATE TRIGGER on_auth_user_login AFTER UPDATE OF last_sign_in_at ON auth.users FOR EACH ROW EXECUTE FUNCTION public.log_login();
CREATE TRIGGER audit_requests AFTER INSERT OR UPDATE ON public.requests FOR EACH ROW EXECUTE FUNCTION public.audit_requests();
CREATE TRIGGER audit_attachments AFTER INSERT ON public.attachments FOR EACH ROW EXECUTE FUNCTION public.audit_attachments();

-- Sécurité (version corrigée le 08/10 : pas d'accès anonyme)
revoke execute on function public.audit_attachments(), public.audit_requests(), public.handle_new_user(),
  public.log_login(), public.resolve_role(text) from public, anon, authenticated;
revoke execute on function public.my_role() from public, anon;
grant execute on function public.my_role() to authenticated;

alter table public.employees enable row level security;
alter table public.role_rules enable row level security;
alter table public.request_types enable row level security;
alter table public.requests enable row level security;
alter table public.attachments enable row level security;
alter table public.projects enable row level security;
alter table public.audit_logs enable row level security;

create policy "employees read" on public.employees for select to authenticated using (true);
create policy "employees update self" on public.employees for update to authenticated using (id = auth.uid()) with check (id = auth.uid());
create policy "types read" on public.request_types for select to authenticated using (true);
create policy "requests insert own" on public.requests for insert to authenticated with check (employee_id = auth.uid());
create policy "requests select" on public.requests for select to authenticated
  using (employee_id = auth.uid() or manager_id = auth.uid() or public.my_role() in ('rh','admin'));
create policy "requests update manager" on public.requests for update to authenticated
  using (manager_id = auth.uid() or public.my_role() in ('rh','admin'));
create policy "attachments insert own request" on public.attachments for insert to authenticated
  with check (exists (select 1 from public.requests r where r.id = attachments.request_id and r.employee_id = auth.uid()));
create policy "attachments select" on public.attachments for select to authenticated
  using (exists (select 1 from public.requests r where r.id = attachments.request_id));
create policy "projects select" on public.projects for select to authenticated
  using (public.my_role() in ('manager','direction','rh','admin'));
create policy "audit read rh/admin" on public.audit_logs for select to authenticated
  using (public.my_role() in ('rh','admin'));

-- Données présentes au moment de la suppression
insert into public.request_types (code, label, default_days) values
  ('conge','Congé',7), ('materiel','Matériel',7), ('remboursement','Remboursement',7), ('autre','Autre',7);
insert into public.role_rules (id, match_type, match_value, role) values
  (1,'email','ton.email@novacorp.fr','admin'), (2,'email','kimijohson@gmail.com','admin');
-- L'employé kimijohson@gmail.com (id 19058f6c-5618-41e9-b2b5-90e69f0a5baf) est recréé automatiquement
-- à partir de son compte Supabase Auth, qui n'a pas été supprimé :
insert into public.employees (id, email, role, created_at)
  values ('19058f6c-5618-41e9-b2b5-90e69f0a5baf', 'kimijohson@gmail.com', 'admin', '2026-10-08 09:27:03.444767+00')
  on conflict do nothing;
